### ISSUE TITLE
Matching multiple elements?

### ISSUE THREAD

**Issue by tophermurphy** [ChrisCavs/rallax.js#1]
Great Plugin!!

I was wondering if you can match multiple elements on a single rallax() call or do you need to define a new const for each one.

**Comment by ChrisCavs** [comment]
Thanks for your support!

As of right now, you cannot match multiple elements with a single call to `rallax()`.  If you provide a class that matches multiple elements, only the first element will have the effect applied.  If you would like to apply rallax to many elements, I would advise doing it this way:

```es6
const elements = Array.from(document.querySelectorAll('.parallax'))

elements.map(el => rallax(el, options))
```

The result will be an array of rallax objects that you can manipulate, one for each element you targeted.

**Comment by tophermurphy** [comment]
Thank works perfectly.

Thank you for your help.

Chris
