### ISSUE TITLE
GPU acceleration / 3d transforms

### ISSUE THREAD

**Issue by atomiks** [ChrisCavs/rallax.js#4]
In Chrome, I'm noticing an fps of around 40 when scrolling past the image. When I add `will-change: transform` to it (accelerate the layer), it increases to 60 fps.

Should 3d transforms be default (`translate3d` instead of `translateY`), or make the user specify `will-change: transform`?

**Comment by ChrisCavs** [comment]
An interesting point, thanks for opening this.  It seems like the browser compatibility for 3d transforms is not as verbose.  Additionally, the `will-change` signal only works on chrome, and shouldn't be used by default in a 3rd party plugin.  I'd say that it should be up to the user to add if they so choose.
